load("@build_bazel_rules_apple//apple:macos.bzl", "macos_application")
load("@build_bazel_rules_swift//swift:swift_library.bzl", "swift_library")

swift_library(
    name = "CharlesRSLib",
    srcs = glob(["*.swift"]) + ["//rust-core:generated/swift/charles_core.swift"],
    module_name = "CharlesRS",
    deps = [
        "//rust-core:charles_core_static",
        "//rust-core:charles_coreFFI",
    ],
    linkopts = [
        "-framework",
        "SystemConfiguration",
        "-framework",
        "Security",
        "-lc++",
    ],
)

macos_application(
    name = "CharlesRS",
    bundle_id = "com.sandeep.charlesrs.app",
    entitlements = "CharlesRS.entitlements",
    infoplists = ["//bazel:Info.plist"],
    minimum_os_version = "14.0",
    deps = [":CharlesRSLib"],
    visibility = ["//visibility:public"],
)
