// `CharlesController` is generated by UniFFI and, being a plain Swift
// class, isn't `Sendable` by default — so under strict concurrency it can't
// cross into a background `Task` without this. It's genuinely safe to: the
// Rust side guards every piece of shared state (`captured`, `mock_rules`,
// `state`) behind `parking_lot::Mutex`/`Mutex`, so calls from any thread are
// synchronized on the Rust side regardless of what Swift's checker can see.
// That's exactly what `@unchecked` is for — asserting a guarantee the
// compiler has no way to verify itself.
extension CharlesController: @unchecked Sendable {}

// These are plain UniFFI-generated value structs — every stored property is
// itself Sendable (String/Bool/Optional/Array-of-those), verified by
// inspection. A plain `Sendable` conformance would be preferable (nothing
// here is actually unchecked), but Swift requires non-`@unchecked`
// retroactive conformances to live in the same file as the type, which we
// don't control for generated bindings — hence `@unchecked` here too, for
// a guarantee that's fully checkable, just not by the compiler itself.
extension MockRule: @unchecked Sendable {}
extension MapLocalRule: @unchecked Sendable {}
extension MapRemoteRule: @unchecked Sendable {}
extension RewriteRule: @unchecked Sendable {}
extension RewriteAction: @unchecked Sendable {}
extension BlockRule: @unchecked Sendable {}
extension DnsSpoofRule: @unchecked Sendable {}
extension FocusSettings: @unchecked Sendable {}
extension HeaderPair: @unchecked Sendable {}
extension CapturedRequest: @unchecked Sendable {}
extension ThrottleProfile: @unchecked Sendable {}
